#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

sudo: required
language: bash
services: docker
os: linux

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda;
  - export PATH="$HOME/miniconda/bin:$PATH";
  - curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
  - sudo install minikube-linux-amd64 /usr/local/bin/minikube
  - minikube start --driver docker
  - conda install -y -c conda-forge mamba;
  - conda info -a
  - mamba env create
  - source activate xcube-hub
  - python setup.py install

script:
  - py.test -v --cov=xcube-hub
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION


