#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

sudo: required
language: bash

os:
  - linux
  - osx
  - windows

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
    elif [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install -y openssl;
      choco install -y miniconda3;
      export PATH="/c/tools/miniconda3/Scripts:$PATH";
      source activate base;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      bash miniconda.sh -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";
      conda install -y -c conda-forge postgis;
    fi

  - conda install -y -c conda-forge mamba;
  - conda info -a
  - mamba env create
  - source activate xcube-hub
  - python setup.py install

script:
  - py.test -v --cov=xcube-hub
  - pip install codecov
  - codecov --env TRAVIS_PYTHON_VERSION


