#
# This is a basic build configuration for Travis CI.
# See http://conda.pydata.org/docs/travis.html for more info.
#

version: '{build}'

image:
  - macOS
  - Ubuntu2004

configuration: Release

platform:
  - x64

install:
  - export UNITTEST_WITH_K8S=true
  - bash ci/install.sh
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda install -y -c conda-forge mamba
  - conda info -a
  - mamba env create
  - source activate xcube-hub
  - python setup.py install
  - pip install Flask-Testing
  - pip install codecov
  - mv ci/ci.env .env

build_script:
  - py.test -v --cov=xcube_hub
  - codecov --env TRAVIS_PYTHON_VERSION
