name: xcube-hub
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - oauthlib
  - boto3
  - click
  - flask
  - flask-cors
  - geoserver-rest
  - pandas
  - pip
  - python-dotenv
  - python-jose
  - python-keycloak
  - uwsgi

  - pip:
      # Required
      - kubernetes
      - polling2
      - flask_oidc
      - flask_cors
      - flask_testing
      - redis
      - requests_oauthlib
      - connexion
      - plyvel
      - requests-mock
      - python_dateutil
      - setuptools
      - connexion[swagger-ui]
      - pydevd-pycharm

  # testing
  - moto
  - flake8
