name: xcube-gen
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - oauthlib
  - pip
  - click
  - flask
  - flask-cors
  - boto3
  - python-jose
  - pandas

  - pip:
      # Required
      - requests_oauthlib
      - kubernetes

  # testing
  - moto
  - flake8
  - pytest
  - pytest-cov