name: xcube-gen
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - xcube>=0.3.0
  - oauthlib
  - pip
  - click
  - flask

  # Inspection
  - jupyterlab

  - pip:
      # Required
      - requests_oauthlib
      - kubernetes

  # testing
  - flake8
  - pytest
  - pytest-cov