name: xcube-hub
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - oauthlib
  - pip
  - click
  - flask
  - flask-cors
  - boto3
  - python-jose
  - pandas
  - uwsgi
  - python-dotenv

  - pip:
      # Required
      - requests_oauthlib
      - kubernetes
      - polling2
      - plyvel
      - requests-mock
      - flask_oidc
      - flask_cors
      - redis

  # testing
  - moto
  - flake8
  - pytest
  - pytest-cov