name: xcube-hub
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - oauthlib
  - pip
  - click
  - flask
  - flask-cors
  - boto3
  - python-jose
  - pandas
  - uwsgi
  - python-dotenv
  - python-keycloak
  - geoserver-rest

  - pip:
      # Required
      - requests_oauthlib
      - kubernetes
      - polling2
      - plyvel
      - requests-mock
      - flask_oidc
      - flask_cors
      - redis
      - flask_testing
      - connexion == 2.6.0
      - python_dateutil == 2.6.0
      - setuptools >= 21.0.0
      - connexion[swagger-ui]

  # testing
  - moto
  - flake8
  - pytest
  - pytest-cov
