name: xcube-gen
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - oauthlib
  - pip
  - click
  - flask
  - flask-cors
  - matplotlib-base

  # Inspection
  - jupyterlab

  - pip:
      # Required
      - requests_oauthlib
      - python-jose
      - kubernetes

  # testing
  - flake8
  - pytest
  - pytest-cov