name: xcube-hub
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - oauthlib
  - boto3
  - click
  - connexion
  - flask
  - flask-cors
  - flask-oidc
  - geoserver-rest
  - pandas
  - pip
  - python-dateutil
  - python-dotenv
  - python-jose
  - python-kubernetes
  # needs 0.24 to avoid issue with urllib3 (https://github.com/marcospereirampj/python-keycloak/issues/196)
  - python-keycloak=0.24.0
  - requests-oauthlib
  - setuptools
  - uwsgi

  - pip:
      # Required
      - connexion[swagger-ui]
      - plyvel
      - polling2
      - redis

