# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub.models.cubegen import Cubegen
from xcube_hub import util

from xcube_hub.models.cubegen import Cubegen  # noqa: E501

class ApiCubegensResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """ApiCubegensResponseAllOf - a model defined in OpenAPI

        :param result: The result of this ApiCubegensResponseAllOf.  # noqa: E501
        :type result: List[Cubegen]
        """
        self.openapi_types = {
            'result': List[Cubegen]
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ApiCubegensResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiCubegensResponse_allOf of this ApiCubegensResponseAllOf.  # noqa: E501
        :rtype: ApiCubegensResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self):
        """Gets the result of this ApiCubegensResponseAllOf.


        :return: The result of this ApiCubegensResponseAllOf.
        :rtype: List[Cubegen]
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this ApiCubegensResponseAllOf.


        :param result: The result of this ApiCubegensResponseAllOf.
        :type result: List[Cubegen]
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result
