# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub.models.callback import Callback
from xcube_hub import util

from xcube_hub.models.callback import Callback  # noqa: E501

class ApiCallbacksResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, result=None):  # noqa: E501
        """ApiCallbacksResponseAllOf - a model defined in OpenAPI

        :param result: The result of this ApiCallbacksResponseAllOf.  # noqa: E501
        :type result: List[Callback]
        """
        self.openapi_types = {
            'result': List[Callback]
        }

        self.attribute_map = {
            'result': 'result'
        }

        self._result = result

    @classmethod
    def from_dict(cls, dikt) -> 'ApiCallbacksResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiCallbacksResponse_allOf of this ApiCallbacksResponseAllOf.  # noqa: E501
        :rtype: ApiCallbacksResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def result(self):
        """Gets the result of this ApiCallbacksResponseAllOf.


        :return: The result of this ApiCallbacksResponseAllOf.
        :rtype: List[Callback]
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this ApiCallbacksResponseAllOf.


        :param result: The result of this ApiCallbacksResponseAllOf.
        :type result: List[Callback]
        """
        if result is None:
            raise ValueError("Invalid value for `result`, must not be `None`")  # noqa: E501

        self._result = result
