# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class ApiErrorResponseAllOf(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, traceback=None):  # noqa: E501
        """ApiErrorResponseAllOf - a model defined in OpenAPI

        :param traceback: The traceback of this ApiErrorResponseAllOf.  # noqa: E501
        :type traceback: object
        """
        self.openapi_types = {
            'traceback': object
        }

        self.attribute_map = {
            'traceback': 'traceback'
        }

        self._traceback = traceback

    @classmethod
    def from_dict(cls, dikt) -> 'ApiErrorResponseAllOf':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The ApiErrorResponse_allOf of this ApiErrorResponseAllOf.  # noqa: E501
        :rtype: ApiErrorResponseAllOf
        """
        return util.deserialize_model(dikt, cls)

    @property
    def traceback(self):
        """Gets the traceback of this ApiErrorResponseAllOf.


        :return: The traceback of this ApiErrorResponseAllOf.
        :rtype: object
        """
        return self._traceback

    @traceback.setter
    def traceback(self, traceback):
        """Sets the traceback of this ApiErrorResponseAllOf.


        :param traceback: The traceback of this ApiErrorResponseAllOf.
        :type traceback: object
        """

        self._traceback = traceback
