# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class CostConfig(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """CostConfig - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'CostConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CostConfig of this CostConfig.  # noqa: E501
        :rtype: CostConfig
        """
        return util.deserialize_model(dikt, cls)
