# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class CubeGenStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, logs: List[str] = None, active: bool = None, start_time: datetime = None, failed: bool = None,
                 succeeded: bool = None, completion_time: datetime = None):  # noqa: E501
        """CubeGenStatus - a model defined in Swagger

        :param logs: The logs of this CubeGenStatus.  # noqa: E501
        :type logs: List[str]
        :param active: The active of this CubeGenStatus.  # noqa: E501
        :type active: bool
        :param start_time: The start_time of this CubeGenStatus.  # noqa: E501
        :type start_time: datetime
        :param failed: The failed of this CubeGenStatus.  # noqa: E501
        :type failed: bool
        :param succeeded: The succeeded of this CubeGenStatus.  # noqa: E501
        :type succeeded: bool
        :param completion_time: The completion_time of this CubeGenStatus.  # noqa: E501
        :type completion_time: datetime
        """
        self.swagger_types = {
            'logs': List[str],
            'active': bool,
            'start_time': datetime,
            'failed': bool,
            'succeeded': bool,
            'completion_time': datetime
        }

        self.attribute_map = {
            'logs': 'logs',
            'active': 'active',
            'start_time': 'start_time',
            'failed': 'failed',
            'succeeded': 'succeeded',
            'completion_time': 'completion_time'
        }
        self._logs = logs
        self._active = active
        self._start_time = start_time
        self._failed = failed
        self._succeeded = succeeded
        self._completion_time = completion_time

    @classmethod
    def from_dict(cls, dikt) -> 'CubeGenStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CubeGenStatus of this CubeGenStatus.  # noqa: E501
        :rtype: CubeGenStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logs(self) -> List[str]:
        """Gets the logs of this CubeGenStatus.


        :return: The logs of this CubeGenStatus.
        :rtype: List[str]
        """
        return self._logs

    @logs.setter
    def logs(self, logs: List[str]):
        """Sets the logs of this CubeGenStatus.


        :param logs: The logs of this CubeGenStatus.
        :type logs: List[str]
        """

        self._logs = logs

    @property
    def active(self) -> bool:
        """Gets the active of this CubeGenStatus.


        :return: The active of this CubeGenStatus.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active: bool):
        """Sets the active of this CubeGenStatus.


        :param active: The active of this CubeGenStatus.
        :type active: bool
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def start_time(self) -> datetime:
        """Gets the start_time of this CubeGenStatus.


        :return: The start_time of this CubeGenStatus.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time: datetime):
        """Sets the start_time of this CubeGenStatus.


        :param start_time: The start_time of this CubeGenStatus.
        :type start_time: datetime
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def failed(self) -> bool:
        """Gets the failed of this CubeGenStatus.


        :return: The failed of this CubeGenStatus.
        :rtype: bool
        """
        return self._failed

    @failed.setter
    def failed(self, failed: bool):
        """Sets the failed of this CubeGenStatus.


        :param failed: The failed of this CubeGenStatus.
        :type failed: bool
        """
        if failed is None:
            raise ValueError("Invalid value for `failed`, must not be `None`")  # noqa: E501

        self._failed = failed

    @property
    def succeeded(self) -> bool:
        """Gets the succeeded of this CubeGenStatus.


        :return: The succeeded of this CubeGenStatus.
        :rtype: bool
        """
        return self._succeeded

    @succeeded.setter
    def succeeded(self, succeeded: bool):
        """Sets the succeeded of this CubeGenStatus.


        :param succeeded: The succeeded of this CubeGenStatus.
        :type succeeded: bool
        """
        if succeeded is None:
            raise ValueError("Invalid value for `succeeded`, must not be `None`")  # noqa: E501

        self._succeeded = succeeded

    @property
    def completion_time(self) -> datetime:
        """Gets the completion_time of this CubeGenStatus.


        :return: The completion_time of this CubeGenStatus.
        :rtype: datetime
        """
        return self._completion_time

    @completion_time.setter
    def completion_time(self, completion_time: datetime):
        """Sets the completion_time of this CubeGenStatus.


        :param completion_time: The completion_time of this CubeGenStatus.
        :type completion_time: datetime
        """
        if completion_time is None:
            raise ValueError("Invalid value for `completion_time`, must not be `None`")  # noqa: E501

        self._completion_time = completion_time
