# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class CubeGenConfigCubeConfigs(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, variable_names: List[str] = None, crs: str = None, spatial_res: float = None,
                 bbox: List[float] = None, time_range: List[date] = None, time_period: str = None):  # noqa: E501
        """CubeGenConfigCubeConfigs - a model defined in Swagger

        :param variable_names: The variable_names of this CubeGenConfigCubeConfigs.  # noqa: E501
        :type variable_names: List[str]
        :param crs: The crs of this CubeGenConfigCubeConfigs.  # noqa: E501
        :type crs: str
        :param spatial_res: The spatial_res of this CubeGenConfigCubeConfigs.  # noqa: E501
        :type spatial_res: float
        :param bbox: The bbox of this CubeGenConfigCubeConfigs.  # noqa: E501
        :type bbox: List[float]
        :param time_range: The time_range of this CubeGenConfigCubeConfigs.  # noqa: E501
        :type time_range: List[date]
        :param time_period: The time_period of this CubeGenConfigCubeConfigs.  # noqa: E501
        :type time_period: str
        """
        self.swagger_types = {
            'variable_names': List[str],
            'crs': str,
            'spatial_res': float,
            'bbox': List[float],
            'time_range': List[date],
            'time_period': str
        }

        self.attribute_map = {
            'variable_names': 'variable_names',
            'crs': 'crs',
            'spatial_res': 'spatial_res',
            'bbox': 'bbox',
            'time_range': 'time_range',
            'time_period': 'time_period'
        }
        self._variable_names = variable_names
        self._crs = crs
        self._spatial_res = spatial_res
        self._bbox = bbox
        self._time_range = time_range
        self._time_period = time_period

    @classmethod
    def from_dict(cls, dikt) -> 'CubeGenConfigCubeConfigs':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CubeGenConfig_cube_configs of this CubeGenConfigCubeConfigs.  # noqa: E501
        :rtype: CubeGenConfigCubeConfigs
        """
        return util.deserialize_model(dikt, cls)

    @property
    def variable_names(self) -> List[str]:
        """Gets the variable_names of this CubeGenConfigCubeConfigs.


        :return: The variable_names of this CubeGenConfigCubeConfigs.
        :rtype: List[str]
        """
        return self._variable_names

    @variable_names.setter
    def variable_names(self, variable_names: List[str]):
        """Sets the variable_names of this CubeGenConfigCubeConfigs.


        :param variable_names: The variable_names of this CubeGenConfigCubeConfigs.
        :type variable_names: List[str]
        """
        if variable_names is None:
            raise ValueError("Invalid value for `variable_names`, must not be `None`")  # noqa: E501

        self._variable_names = variable_names

    @property
    def crs(self) -> str:
        """Gets the crs of this CubeGenConfigCubeConfigs.


        :return: The crs of this CubeGenConfigCubeConfigs.
        :rtype: str
        """
        return self._crs

    @crs.setter
    def crs(self, crs: str):
        """Sets the crs of this CubeGenConfigCubeConfigs.


        :param crs: The crs of this CubeGenConfigCubeConfigs.
        :type crs: str
        """
        if crs is None:
            raise ValueError("Invalid value for `crs`, must not be `None`")  # noqa: E501

        self._crs = crs

    @property
    def spatial_res(self) -> float:
        """Gets the spatial_res of this CubeGenConfigCubeConfigs.


        :return: The spatial_res of this CubeGenConfigCubeConfigs.
        :rtype: float
        """
        return self._spatial_res

    @spatial_res.setter
    def spatial_res(self, spatial_res: float):
        """Sets the spatial_res of this CubeGenConfigCubeConfigs.


        :param spatial_res: The spatial_res of this CubeGenConfigCubeConfigs.
        :type spatial_res: float
        """
        if spatial_res is None:
            raise ValueError("Invalid value for `spatial_res`, must not be `None`")  # noqa: E501

        self._spatial_res = spatial_res

    @property
    def bbox(self) -> List[float]:
        """Gets the bbox of this CubeGenConfigCubeConfigs.


        :return: The bbox of this CubeGenConfigCubeConfigs.
        :rtype: List[float]
        """
        return self._bbox

    @bbox.setter
    def bbox(self, bbox: List[float]):
        """Sets the bbox of this CubeGenConfigCubeConfigs.


        :param bbox: The bbox of this CubeGenConfigCubeConfigs.
        :type bbox: List[float]
        """
        if bbox is None:
            raise ValueError("Invalid value for `bbox`, must not be `None`")  # noqa: E501

        self._bbox = bbox

    @property
    def time_range(self) -> List[date]:
        """Gets the time_range of this CubeGenConfigCubeConfigs.


        :return: The time_range of this CubeGenConfigCubeConfigs.
        :rtype: List[date]
        """
        return self._time_range

    @time_range.setter
    def time_range(self, time_range: List[date]):
        """Sets the time_range of this CubeGenConfigCubeConfigs.


        :param time_range: The time_range of this CubeGenConfigCubeConfigs.
        :type time_range: List[date]
        """
        if time_range is None:
            raise ValueError("Invalid value for `time_range`, must not be `None`")  # noqa: E501

        self._time_range = time_range

    @property
    def time_period(self) -> str:
        """Gets the time_period of this CubeGenConfigCubeConfigs.


        :return: The time_period of this CubeGenConfigCubeConfigs.
        :rtype: str
        """
        return self._time_period

    @time_period.setter
    def time_period(self, time_period: str):
        """Sets the time_period of this CubeGenConfigCubeConfigs.


        :param time_period: The time_period of this CubeGenConfigCubeConfigs.
        :type time_period: str
        """
        if time_period is None:
            raise ValueError("Invalid value for `time_period`, must not be `None`")  # noqa: E501

        self._time_period = time_period
