# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class CubegenConfigCodeConfigFileSet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, path=None):  # noqa: E501
        """CubegenConfigCodeConfigFileSet - a model defined in OpenAPI

        :param path: The path of this CubegenConfigCodeConfigFileSet.  # noqa: E501
        :type path: str
        """
        self.openapi_types = {
            'path': str
        }

        self.attribute_map = {
            'path': 'path'
        }

        self._path = path

    @classmethod
    def from_dict(cls, dikt) -> 'CubegenConfigCodeConfigFileSet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CubegenConfigCodeConfig_file_set of this CubegenConfigCodeConfigFileSet.  # noqa: E501
        :rtype: CubegenConfigCodeConfigFileSet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def path(self):
        """Gets the path of this CubegenConfigCodeConfigFileSet.


        :return: The path of this CubegenConfigCodeConfigFileSet.
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this CubegenConfigCodeConfigFileSet.


        :param path: The path of this CubegenConfigCodeConfigFileSet.
        :type path: str
        """

        self._path = path
