# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class CubegenStatus(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, logs=None, active=None, start_time=None, failed=None, succeeded=None, completion_time=None):  # noqa: E501
        """CubegenStatus - a model defined in OpenAPI

        :param logs: The logs of this CubegenStatus.  # noqa: E501
        :type logs: List[str]
        :param active: The active of this CubegenStatus.  # noqa: E501
        :type active: bool
        :param start_time: The start_time of this CubegenStatus.  # noqa: E501
        :type start_time: datetime
        :param failed: The failed of this CubegenStatus.  # noqa: E501
        :type failed: bool
        :param succeeded: The succeeded of this CubegenStatus.  # noqa: E501
        :type succeeded: bool
        :param completion_time: The completion_time of this CubegenStatus.  # noqa: E501
        :type completion_time: datetime
        """
        self.openapi_types = {
            'logs': List[str],
            'active': bool,
            'start_time': datetime,
            'failed': bool,
            'succeeded': bool,
            'completion_time': datetime
        }

        self.attribute_map = {
            'logs': 'logs',
            'active': 'active',
            'start_time': 'start_time',
            'failed': 'failed',
            'succeeded': 'succeeded',
            'completion_time': 'completion_time'
        }

        self._logs = logs
        self._active = active
        self._start_time = start_time
        self._failed = failed
        self._succeeded = succeeded
        self._completion_time = completion_time

    @classmethod
    def from_dict(cls, dikt) -> 'CubegenStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The CubegenStatus of this CubegenStatus.  # noqa: E501
        :rtype: CubegenStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def logs(self):
        """Gets the logs of this CubegenStatus.


        :return: The logs of this CubegenStatus.
        :rtype: List[str]
        """
        return self._logs

    @logs.setter
    def logs(self, logs):
        """Sets the logs of this CubegenStatus.


        :param logs: The logs of this CubegenStatus.
        :type logs: List[str]
        """

        self._logs = logs

    @property
    def active(self):
        """Gets the active of this CubegenStatus.


        :return: The active of this CubegenStatus.
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this CubegenStatus.


        :param active: The active of this CubegenStatus.
        :type active: bool
        """
        if active is None:
            raise ValueError("Invalid value for `active`, must not be `None`")  # noqa: E501

        self._active = active

    @property
    def start_time(self):
        """Gets the start_time of this CubegenStatus.


        :return: The start_time of this CubegenStatus.
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this CubegenStatus.


        :param start_time: The start_time of this CubegenStatus.
        :type start_time: datetime
        """
        if start_time is None:
            raise ValueError("Invalid value for `start_time`, must not be `None`")  # noqa: E501

        self._start_time = start_time

    @property
    def failed(self):
        """Gets the failed of this CubegenStatus.


        :return: The failed of this CubegenStatus.
        :rtype: bool
        """
        return self._failed

    @failed.setter
    def failed(self, failed):
        """Sets the failed of this CubegenStatus.


        :param failed: The failed of this CubegenStatus.
        :type failed: bool
        """
        if failed is None:
            raise ValueError("Invalid value for `failed`, must not be `None`")  # noqa: E501

        self._failed = failed

    @property
    def succeeded(self):
        """Gets the succeeded of this CubegenStatus.


        :return: The succeeded of this CubegenStatus.
        :rtype: bool
        """
        return self._succeeded

    @succeeded.setter
    def succeeded(self, succeeded):
        """Sets the succeeded of this CubegenStatus.


        :param succeeded: The succeeded of this CubegenStatus.
        :type succeeded: bool
        """
        if succeeded is None:
            raise ValueError("Invalid value for `succeeded`, must not be `None`")  # noqa: E501

        self._succeeded = succeeded

    @property
    def completion_time(self):
        """Gets the completion_time of this CubegenStatus.


        :return: The completion_time of this CubegenStatus.
        :rtype: datetime
        """
        return self._completion_time

    @completion_time.setter
    def completion_time(self, completion_time):
        """Sets the completion_time of this CubegenStatus.


        :param completion_time: The completion_time of this CubegenStatus.
        :type completion_time: datetime
        """
        if completion_time is None:
            raise ValueError("Invalid value for `completion_time`, must not be `None`")  # noqa: E501

        self._completion_time = completion_time
