# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub.models.dataset import Dataset  # noqa: F401,E501
from xcube_hub import util


class Datastore(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: str=None, name: str=None, datasets: List[Dataset]=None):  # noqa: E501
        """Datastore - a model defined in Swagger

        :param id: The id of this Datastore.  # noqa: E501
        :type id: str
        :param name: The name of this Datastore.  # noqa: E501
        :type name: str
        :param datasets: The datasets of this Datastore.  # noqa: E501
        :type datasets: List[Dataset]
        """
        self.swagger_types = {
            'id': str,
            'name': str,
            'datasets': List[Dataset]
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'datasets': 'datasets'
        }
        self._id = id
        self._name = name
        self._datasets = datasets

    @classmethod
    def from_dict(cls, dikt) -> 'Datastore':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Datastore of this Datastore.  # noqa: E501
        :rtype: Datastore
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this Datastore.


        :return: The id of this Datastore.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this Datastore.


        :param id: The id of this Datastore.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Datastore.


        :return: The name of this Datastore.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Datastore.


        :param name: The name of this Datastore.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def datasets(self) -> List[Dataset]:
        """Gets the datasets of this Datastore.


        :return: The datasets of this Datastore.
        :rtype: List[Dataset]
        """
        return self._datasets

    @datasets.setter
    def datasets(self, datasets: List[Dataset]):
        """Sets the datasets of this Datastore.


        :param datasets: The datasets of this Datastore.
        :type datasets: List[Dataset]
        """
        if datasets is None:
            raise ValueError("Invalid value for `datasets`, must not be `None`")  # noqa: E501

        self._datasets = datasets
