# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class DataStoreStoreParams(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, api_url=None):  # noqa: E501
        """DataStoreStoreParams - a model defined in OpenAPI

        :param api_url: The api_url of this DataStoreStoreParams.  # noqa: E501
        :type api_url: str
        """
        self.openapi_types = {
            'api_url': str
        }

        self.attribute_map = {
            'api_url': 'api_url'
        }

        self._api_url = api_url

    @classmethod
    def from_dict(cls, dikt) -> 'DataStoreStoreParams':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataStore_store_params of this DataStoreStoreParams.  # noqa: E501
        :rtype: DataStoreStoreParams
        """
        return util.deserialize_model(dikt, cls)

    @property
    def api_url(self):
        """Gets the api_url of this DataStoreStoreParams.


        :return: The api_url of this DataStoreStoreParams.
        :rtype: str
        """
        return self._api_url

    @api_url.setter
    def api_url(self, api_url):
        """Sets the api_url of this DataStoreStoreParams.


        :param api_url: The api_url of this DataStoreStoreParams.
        :type api_url: str
        """

        self._api_url = api_url
