# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util

from xcube_hub.models.data_store_cost_params import DataStoreCostParams  # noqa: E501
from xcube_hub.models.data_store_store_params import DataStoreStoreParams  # noqa: E501


class DataStore(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, store_id=None, cost_params=None, store_params=None):  # noqa: E501
        """DataStore - a model defined in OpenAPI

        :param title: The title of this DataStore.  # noqa: E501
        :type title: str
        :param store_id: The store_id of this DataStore.  # noqa: E501
        :type store_id: str
        :param cost_params: The cost_params of this DataStore.  # noqa: E501
        :type cost_params: DataStoreCostParams
        :param store_params: The store_params of this DataStore.  # noqa: E501
        :type store_params: DataStoreStoreParams
        """
        self.openapi_types = {
            'title': str,
            'store_id': str,
            'cost_params': DataStoreCostParams,
            'store_params': DataStoreStoreParams
        }

        self.attribute_map = {
            'title': 'title',
            'store_id': 'store_id',
            'cost_params': 'cost_params',
            'store_params': 'store_params'
        }

        self._title = title
        self._store_id = store_id
        self._cost_params = cost_params
        self._store_params = store_params

    @classmethod
    def from_dict(cls, dikt) -> 'DataStore':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DataStore of this DataStore.  # noqa: E501
        :rtype: DataStore
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self):
        """Gets the title of this DataStore.


        :return: The title of this DataStore.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this DataStore.


        :param title: The title of this DataStore.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def store_id(self):
        """Gets the store_id of this DataStore.


        :return: The store_id of this DataStore.
        :rtype: str
        """
        return self._store_id

    @store_id.setter
    def store_id(self, store_id):
        """Sets the store_id of this DataStore.


        :param store_id: The store_id of this DataStore.
        :type store_id: str
        """
        if store_id is None:
            raise ValueError("Invalid value for `store_id`, must not be `None`")  # noqa: E501

        self._store_id = store_id

    @property
    def cost_params(self):
        """Gets the cost_params of this DataStore.


        :return: The cost_params of this DataStore.
        :rtype: DataStoreCostParams
        """
        return self._cost_params

    @cost_params.setter
    def cost_params(self, cost_params):
        """Sets the cost_params of this DataStore.


        :param cost_params: The cost_params of this DataStore.
        :type cost_params: DataStoreCostParams
        """
        if cost_params is None:
            raise ValueError("Invalid value for `cost_params`, must not be `None`")  # noqa: E501

        self._cost_params = cost_params

    @property
    def store_params(self):
        """Gets the store_params of this DataStore.


        :return: The store_params of this DataStore.
        :rtype: DataStoreStoreParams
        """
        return self._store_params

    @store_params.setter
    def store_params(self, store_params):
        """Sets the store_params of this DataStore.


        :param store_params: The store_params of this DataStore.
        :type store_params: DataStoreStoreParams
        """
        if store_params is None:
            raise ValueError("Invalid value for `store_params`, must not be `None`")  # noqa: E501

        self._store_params = store_params
