# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class OAuthToken(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, client_id: str = None, client_secret: str = None, audience: str = None,
                 grant_type: str = None):  # noqa: E501
        """OAuthToken - a model defined in Swagger

        :param client_id: The client_id of this OAuthToken.  # noqa: E501
        :type client_id: str
        :param client_secret: The client_secret of this OAuthToken.  # noqa: E501
        :type client_secret: str
        :param audience: The audience of this OAuthToken.  # noqa: E501
        :type audience: str
        :param grant_type: The grant_type of this OAuthToken.  # noqa: E501
        :type grant_type: str
        """
        self.swagger_types = {
            'client_id': str,
            'client_secret': str,
            'audience': str,
            'grant_type': str
        }

        self.attribute_map = {
            'client_id': 'client_id',
            'client_secret': 'client_secret',
            'audience': 'audience',
            'grant_type': 'grant_type'
        }
        self._client_id = client_id
        self._client_secret = client_secret
        self._audience = audience
        self._grant_type = grant_type

    @classmethod
    def from_dict(cls, dikt) -> 'OAuthToken':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OAuthToken of this OAuthToken.  # noqa: E501
        :rtype: OAuthToken
        """
        return util.deserialize_model(dikt, cls)

    @property
    def client_id(self) -> str:
        """Gets the client_id of this OAuthToken.


        :return: The client_id of this OAuthToken.
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id: str):
        """Sets the client_id of this OAuthToken.


        :param client_id: The client_id of this OAuthToken.
        :type client_id: str
        """
        if client_id is None:
            raise ValueError("Invalid value for `client_id`, must not be `None`")  # noqa: E501

        self._client_id = client_id

    @property
    def client_secret(self) -> str:
        """Gets the client_secret of this OAuthToken.


        :return: The client_secret of this OAuthToken.
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret: str):
        """Sets the client_secret of this OAuthToken.


        :param client_secret: The client_secret of this OAuthToken.
        :type client_secret: str
        """
        if client_secret is None:
            raise ValueError("Invalid value for `client_secret`, must not be `None`")  # noqa: E501

        self._client_secret = client_secret

    @property
    def audience(self) -> str:
        """Gets the audience of this OAuthToken.


        :return: The audience of this OAuthToken.
        :rtype: str
        """
        return self._audience

    @audience.setter
    def audience(self, audience: str):
        """Sets the audience of this OAuthToken.


        :param audience: The audience of this OAuthToken.
        :type audience: str
        """
        if audience is None:
            raise ValueError("Invalid value for `audience`, must not be `None`")  # noqa: E501

        self._audience = audience

    @property
    def grant_type(self) -> str:
        """Gets the grant_type of this OAuthToken.


        :return: The grant_type of this OAuthToken.
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type: str):
        """Sets the grant_type of this OAuthToken.


        :param grant_type: The grant_type of this OAuthToken.
        :type grant_type: str
        """
        if grant_type is None:
            raise ValueError("Invalid value for `grant_type`, must not be `None`")  # noqa: E501

        self._grant_type = grant_type
