# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from xcube_hub.models.base_model_ import Model
from xcube_hub import util


class Service(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, service_id=None):  # noqa: E501
        """Service - a model defined in OpenAPI

        :param service_id: The title of this Service.  # noqa: E501
        :type service_id: str
        """
        self.openapi_types = {
            'service_id': str
        }

        self.attribute_map = {
            'service_id': 'service_id'
        }

        self._service_id = service_id

    @classmethod
    def from_dict(cls, dikt) -> 'Service':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Service of this Service.  # noqa: E501
        :rtype: Service
        """
        return util.deserialize_model(dikt, cls)

    @property
    def service_id(self):
        """Gets the service_id of this Service.


        :return: The service_id of this Service.
        :rtype: str
        """
        return self._service_id

    @service_id.setter
    def service_id(self, service_id):
        """Sets the service_id of this Service.


        :param service_id: The service_id of this Service.
        :type service_id: str
        """
        if service_id is None:
            raise ValueError("Invalid value for `service_id`, must not be `None`")  # noqa: E501

        self._service_id = service_id
