openapi: 3.0.0
info:
  contact:
    email: info@brockmann-consult.de
  description: Restful API for handling xcube Services
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: xcube Generator API
  version: 2.1.0.dev2
servers:
  - url: https://xcube-gen.brockmann-consult.de/api/v2
  - url: https://stage.xcube-gen.brockmann-consult.de/api/v2
  - url: https://xcube-geodb.brockmann-consult.de/api/v2
  - url: https://stage.xcube-geodb.brockmann-consult.de/api/v2
  - url: https://cate.climate.esa.int/api/v2
  - url: https://stage.cate.climate.esa.int/api/v2
tags:
  - name: cubegens
  - name: callbacks
  - name: oauth
  - name: services
  - name: webapis
paths:
  /:
    get:
      description: Get service info
      operationId: get_service_info
      summary: get service info
      x-openapi-router-controller: xcube_hub.controllers.default
  /webapis:
    get:
      description:
        Get running webapis
      operationId: get_webapis
      #      security:
      #        - oAuthorization:
      #            - manage:webapis
      summary: Create a cate service instance
      tags:
        - webapis
      x-openapi-router-controller: xcube_hub.controllers.webapis
  /users/{user_id}/webapis:
    get:
      description: |
        Get webapi information
      operationId: get_user_webapi
#      security:
#        - oAuthorization:
#            - manage:users
      summary: Create a cate service instance
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
    post:
      description: |
        Create a webapi
      operationId: put_user_webapi
#      security:
#        - oAuthorization:
#            - manage:users
      summary: Create a cate service instance
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
    delete:
      description: |
        Delete a webapi
      operationId: delete_user_webapi
#      security:
#        - oAuthorization:
#            - manage:users
      summary: Create a webapi instance
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
  /services:
    get:
      description: |
        get a list of services. Currently, a service can be either of
        - xcube_gen
        - xcube_geodb
        - xcube_geoserv
      operationId: get_services
      summary: Manage services
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /services/{service_id}/subscriptions:
    put:
      description: |
        Register a subscription to a service. A service can either of be
        - xcube_gen
        - xcube_geodb
        - xcube_geoserv
      operationId: put_subscription_to_service
      security:
        - oAuthorization:
            - read:users
            - create:users
      summary: Manage subscriptions for serices
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /services/{service_id}/subscriptions/{subscription_id}:
    get:
      description: |
        Get info about a subscription of a service. A service can either of be
        - xcube_gen
        - xcube_geodb
        - xcube_geoserv
      operationId: get_subscription_from_service
      security:
        - oAuthorization:
            - read:users
            - create:users
      summary: Manage subscriptions
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
    delete:
      description: |
        Delete a subscription from a service.  A service can either of be
        - xcube_gen
        - xcube_geodb
        - xcube_geoserv
      operationId: delete_subscription_from_service
      security:
        - oAuthorization:
            - read:users
            - create:users
      summary: Delete a subscription from a service
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /cubegens:
    delete:
      description: |
        Delete all cubegens
      operationId: delete_cubegens
      security:
        - oAuthorization:
            - manage:cubegens
      summary: Delete all cubegens
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List user cubegens
      operationId: get_cubegens
      security:
        - oAuthorization:
            - manage:cubegens
      summary: List cubegens
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    put:
      description: |
        Create a jcubegen
      operationId: create_cubegen
      security:
        - oAuthorization:
            - manage:cubegens
      summary: Create a cubegen
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/code:
    put:
      description: |
        Create a cubegen passing user code and cube config as json and zip file
      operationId: create_cubegen_code
      security:
        - oAuthorization:
            - manage:cubegens
      summary: Create a cubegen
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/info:
    post:
      description: |
        Receive cost information of using a service
      operationId: get_cubegen_info
      security:
        - oAuthorization:
            - manage:cubegens
      summary: Receive cost information for runnning a cubegen
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}:
    delete:
      description: |
        Delete a cubegen
      operationId: delete_cubegen
      security:
        - oAuthorization:
            - manage:cubegens
      summary: Delete a cubegen
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List specific cubegen
      operationId: get_cubegen
      security:
        - oAuthorization:
            - manage:cubegens
      summary: List specific cubegen
      tags:
        - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}/callbacks:
    put:
      description: Add a callbacks for a cubegen
      operationId: put_callback_by_cubegen_id
      security:
        - oAuthorization:
            - manage:cubegens
      summary: Add a callback for a cubegen
      tags:
        - callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks
  /services/xcube_geoserv/collections:
    get:
      description: Manage GeoDB Collections
      operationId: get_all_collections
      summary: Get authorization token
      security:
        - oAuthorization:
            - manage:collections
      tags:
        - geoservice
      x-openapi-router-controller: xcube_hub.controllers.geoservice
  /services/xcube_geoserv/databases/{database_id}/collections:
    get:
      description: Manage GeoDB Collections
      operationId: get_collections
      summary: Get authorization token
      security:
        - oAuthorization:
            - manage:collections
      tags:
        - geoservice
      x-openapi-router-controller: xcube_hub.controllers.geoservice
    put:
      description: Manage GeoDB Collections
      operationId: put_collection
      summary: Get authorization token
      security:
        - oAuthorization:
            - manage:collections
      tags:
        - geoservice
      x-openapi-router-controller: xcube_hub.controllers.geoservice
  /services/xcube_geoserv/databases/{database_id}/collections/{collection_id}:
    get:
      description: Manage GeoDB Collections
      operationId: get_collection
      summary: Get authorization token
      security:
        - oAuthorization:
            - manage:collections
      tags:
        - geoservice
      x-openapi-router-controller: xcube_hub.controllers.geoservice
    delete:
      description: Manage GeoDB Collections
      operationId: delete_collection
      summary: Get authorization token
      security:
        - oAuthorization:
            - manage:collections
      tags:
        - geoservice
      x-openapi-router-controller: xcube_hub.controllers.geoservice
  /oauth/token:
    post:
      description: Get authorization token
      operationId: oauth_token_post
      summary: Get authorization token
      tags:
        - oauth
      x-openapi-router-controller: xcube_hub.controllers.oauth
components:
  securitySchemes:
    oAuthorization:
      description: This API uses Oauth 2 with the implicit grant flow.
      flows:
        clientCredentials:
          scopes:
            manage_cubegens: Read cubegen status and result
          tokenUrl: https://xcube-users.brockmann-consult.de/auth/realms/xcube/protocol/openid-connect/token
      type: oauth2
      x-tokenInfoFunc: xcube_hub.controllers.authorization.check_oauthorization
      x-scopeValidateFunc: xcube_hub.controllers.authorization.validate_scope_oauthorization