openapi: 3.0.0
info:
  contact:
    email: info@brockmann-consult.de
  description: Restful API for handling xcube Services
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: xcube Generator API
  version: 2.0.0
servers:
- url: https://xcube-gen.brockmann-consult.de/api/v2
- url: https://stage.xcube-gen.brockmann-consult.de/api/v2
tags:
- name: users
- name: cubegens
- name: callbacks
- name: oauth
paths:
  /:
    get:
      description: Get service info
      operationId: get_service_info
      summary: get service info
      x-openapi-router-controller: xcube_hub.controllers.default
  /users:
    put:
      description: |
        Create a user
      operationId: put_user
      security:
        - oAuthorization:
          - create:users
      summary: Create a user
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/{user_id}:
    get:
      description: |
        Get info of a user
      operationId: get_user_by_user_id
      tags:
        - users
      security:
         - oAuthorization:
           - read:users
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/{user_id}/apps:
    get:
      description: |
        Get user's apps
      operationId: get_user_apps
      tags:
        - users
      security:
        - oAuthorization:
            - read:users
            - read:roles
            - read:role_members
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/{user_id}/apps/{app_id}:
    put:
      description: Add user to app
      operationId: put_user_to_app
      tags:
        - users
      security:
        - oAuthorization:
            - update:users
            - read:roles
            - create:role_members
      x-openapi-router-controller: xcube_hub.controllers.users
    delete:
      description: |
        Remove a user from app
      operationId: delete_user_from_app
      tags:
        - users
      security:
        - oAuthorization:
            - update:users
            - delete:role_members
      x-openapi-router-controller: xcube_hub.controllers.users
  /users/credentials:
    get:
      description: |
        Get info of a user
      operationId: get_user_credentials
      security:
        - oAuthorization:
            - read:users
      x-openapi-router-controller: xcube_hub.controllers.users
  /cubegens:
    delete:
      description: |
        Delete all cubegens
      operationId: delete_cubegens
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Delete all cubegens
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List user cubegens
      operationId: get_cubegens
      security:
      - oAuthorization:
        - manage:cubegens
      summary: List cubegens
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    put:
      description: |
        Create a jcubegen
      operationId: create_cubegen
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Create a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/info:
    post:
      description: |
        Receive cost information of using a service
      operationId: get_cubegen_info
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Receive cost information for runnning a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}:
    delete:
      description: |
        Delete a cubegen
      operationId: delete_cubegen
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Delete a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List specific cubegen
      operationId: get_cubegen
      security:
      - oAuthorization:
        - manage:cubegens
      summary: List specific cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}/callbacks:
    put:
      description: Add a callbacks for a cubegen
      operationId: put_callback_by_cubegen_id
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Add a callback for a cubegen
      tags:
      - callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks
  /oauth/token:
    post:
      description: Get authorization token
      operationId: oauth_token_post
#          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OauthToken'
        description: OauthToken
      summary: Get authorization token
      tags:
      - oauth
      x-openapi-router-controller: xcube_hub.controllers.oauth
  /stores:
    get:
      description: Get stores
      operationId: get_stores
      summary: Get stores
      tags:
        - stores
      x-openapi-router-controller: xcube_hub.controllers.stores
components:
  securitySchemes:
    oAuthorization:
      description: This API uses Oauth 2 with the implicit grant flow.
      flows:
        clientCredentials:
          scopes:
            manage_cubegens: Read cubegen status and result
          tokenUrl: http://localhost:8080/api/v2/oauth/token
      type: oauth2
      x-tokenInfoFunc: xcube_hub.controllers.authorization.check_oauthorization
      x-scopeValidateFunc: xcube_hub.controllers.authorization.validate_scope_oauthorization
