openapi: 3.0.0
info:
  contact:
    email: info@brockmann-consult.de
  description: Restful API for handling xcube Services
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: xcube Generator API
  version: 2.0.0
servers:
  - url: https://xcube-gen.brockmann-consult.de/api/v2
  - url: https://stage.xcube-gen.brockmann-consult.de/api/v2
  - url: https://xcube-geodb.brockmann-consult.de/api/v2
  - url: https://stage.xcube-geodb.brockmann-consult.de/api/v2
  - url: https://cate.climate.esa.int/api/v2
  - url: https://stage.cate.climate.esa.int/api/v2
tags:
  - name: cubegens
  - name: webapis
  - name: users
  - name: callbacks
  - name: oauth
  - name: services
paths:
  /:
    get:
      description: Get service info
      operationId: get_service_info
      summary: get service info
      x-openapi-router-controller: xcube_hub.controllers.default
  /services/{service_id}:
    get:
      operationId: get_service
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /services:
    get:
      description: |
        get a list of services
      operationId: get_services
      security:
        - oAuthorization:
            - manage:services
      summary: Manage subscriptions
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /services/{service_id}/subscriptions:
    put:
      description: |
        Register a subscription to a service
      operationId: put_subscription_to_service
      security:
        - oAuthorization:
            - manage:services
      summary: Manage subscriptions for serices
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /services/{service_id}/subscriptions/{subscription_id}:
    get:
      description: |
        Get info about a subscription of a service
      operationId: get_subscription_from_service
      security:
        - oAuthorization:
            - manage:services
      summary: Manage subscriptions
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
    delete:
      description: |
        Delete a subscription
      operationId: delete_subscription_from_service
      security:
        - oAuthorization:
            - manage:services
      summary: Delete a subscription from a service
      tags:
        - services
      x-openapi-router-controller: xcube_hub.controllers.services
  /webapis:
    get:
      description:
        Get running webapis
      operationId: get_webapis
#      security:
#        - oAuthorization:
#            - manage:webapis
      summary: Create a cate service instance
      tags:
        - webapis
      x-openapi-router-controller: xcube_hub.controllers.webapis
  /users/{user_id}/webapis:
    get:
      description: |
        Get webapi information
      operationId: get_user_webapi
      security:
        - oAuthorization:
            - manage:users
      summary: Create a cate service instance
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
    post:
      description: |
        Create a webapi
      operationId: put_user_webapi
      security:
        - oAuthorization:
            - manage:users
      summary: Create a cate service instance
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
    delete:
      description: |
        Delete a webapi
      operationId: delete_user_webapi
      security:
        - oAuthorization:
            - manage:users
      summary: Create a webapi instance
      tags:
        - users
      x-openapi-router-controller: xcube_hub.controllers.users
  /cubegens:
    delete:
      description: |
        Delete all cubegens
      operationId: delete_cubegens
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Delete all cubegens
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List user cubegens
      operationId: get_cubegens
      security:
      - oAuthorization:
        - manage:cubegens
      summary: List cubegens
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    put:
      description: |
        Create a jcubegen
      operationId: create_cubegen
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Create a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/info:
    post:
      description: |
        Receive cost information of using a service
      operationId: get_cubegen_info
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Receive cost information for runnning a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}:
    delete:
      description: |
        Delete a cubegen
      operationId: delete_cubegen
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Delete a cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
    get:
      description: |
        List specific cubegen
      operationId: get_cubegen
      security:
      - oAuthorization:
        - manage:cubegens
      summary: List specific cubegen
      tags:
      - cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens
  /cubegens/{cubegen_id}/callbacks:
    put:
      description: Add a callbacks for a cubegen
      operationId: put_callback_by_cubegen_id
      security:
      - oAuthorization:
        - manage:cubegens
      summary: Add a callback for a cubegen
      tags:
      - callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks
  /oauth/token:
    post:
      description: Get authorization token
      operationId: oauth_token_post
#          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/OauthToken'
        description: OauthToken
      summary: Get authorization token
      tags:
      - oauth
      x-openapi-router-controller: xcube_hub.controllers.oauth
  /stores:
    get:
      description: Get stores
      operationId: get_stores
      summary: Get stores
      tags:
        - stores
      x-openapi-router-controller: xcube_hub.controllers.stores
components:
  securitySchemes:
    oAuthorization:
      description: This API uses Oauth 2 with the implicit grant flow.
      flows:
        clientCredentials:
          scopes:
            manage_cubegens: Read cubegen status and result
          tokenUrl: https://xcube-users.brockmann-consult.de/realms/xcube/protocol/openid-connect/token
      type: oauth2
      x-tokenInfoFunc: xcube_hub.controllers.authorization.check_oauthorization
      x-scopeValidateFunc: xcube_hub.controllers.authorization.validate_scope_oauthorization
