xcube-gen:
  endpoints:
    - "https://stage.xcube-gen.brockmann-consult.de/api/v2"
  auth:
    url: "https://xcube-users.brockmann-consult.de/auth/realms/xcube/protocol/openid-connect/token"
    aud: "https://xcube-gen.brockmann-consult.de/api/v2/"
  status:
    - Ready
  message:
    - OK
  configs:
    cacheProvider: redis
    xcubeDockerRepository: quay.io/bcdev/xcube-gen
    xcubeDockerTag: 0.7.1
    dataPoolsConfig: data-pools.yaml
xcube-geodb:
  endpoints:
    - "https://stage.xcube-geodb.brockmann-consult.de/api/v2"
  auth:
    - "https://xcube-users.brockmann-consult.de/auth/realms/xcube/protocol/openid-connect/token"
  status:
    - Ready
  message:
    - OK
cate:
  endpoints:
    - "https://stage.cate.climate.esa.int/api/v2"
  auth:
    - "https://cateusers.climate.esa.int/auth/realms/cate/protocol/openid-connect/token"
  status:
    - Ready
  message:
    - OK
  configs:
    oidcClientsSecretFile: "client_secrets.json"
    cateLaunchGrace: 2
    cateImage:
    cateVersion:
    cateCommand:
    cateActivateCommand:
    cateUserNamespace:
    cateUserRoot:
    cateServicePreFix:
    cateUserspacePVCName:
    cateUsername:
