openapi: 3.0.0
info:
  title: xcube Generation API
  description: Restful API for handling xcube Services
  contact:
    email: info@brockmann-consult.de
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 2.0.0
servers:
- url: https://xcube-gen.brockmann-consult.de/api/v2
- url: https://stage.xcube-gen.brockmann-consult.de/api/v2
- url: https://catehub.climate.esa.int/api/v2
- url: https://stage.catehub.climate.esa.int/api/v2
tags:
- name: users
- name: cubegens
- name: datastores
- name: callbacks
- name: oauth
paths:
  /:
    get:
      summary: get service info
      description: Get service info
      operationId: get_service_info
      x-openapi-router-controller: xcube_hub.controllers.default_controller
  /datastores:
    get:
      tags:
      - datastores
      summary: Get a list of datastores
      description: Get a list of datastores
      operationId: get_data_stores
      security:
      - oAuthorization:
        - read:datastores
      x-openapi-router-controller: xcube_hub.controllers.datastores_controller
  /datastores/{datastore_id}:
    get:
      tags:
      - datastores
      summary: Get a datastore
      description: Get info of a datastore
      operationId: get_data_store_by_datastore_id
      security:
      - oAuthorization:
        - read:datastores
      x-openapi-router-controller: xcube_hub.controllers.datastores_controller
  /cubegens/costs:
    post:
      tags:
      - cubegens
      summary: Receive cost information for runnning a job
      description: |
        Receive cost information of using a service
      operationId: get_costs
      security:
      - oAuthorization:
        - read:costs
      x-openapi-router-controller: xcube_hub.controllers.cubegens_controller
  /users/{user_id}:
    get:
      tags:
      - users
      summary: Get users
      description: |
        Get user info
      operationId: get_user_by_user_id
      security:
      - oAuthorization:
        - read:users
      x-openapi-router-controller: xcube_hub.controllers.users_controller
    put:
      tags:
      - users
      summary: Add user
      description: |
        Add user
      operationId: add_user
      security:
      - oAuthorization:
        - create:users
      x-openapi-router-controller: xcube_hub.controllers.users_controller
    delete:
      tags:
      - users
      summary: Delete user
      description: |
        Remove user from a service
      operationId: delete_user_by_user_id
      security:
      - oAuthorization:
        - delete:users
      x-openapi-router-controller: xcube_hub.controllers.users_controller
    patch:
      tags:
      - users
      summary: Update user
      description: |
        Update users in a service
      operationId: update_user_by_user_id
      security:
      - oAuthorization:
        - update:users
      x-openapi-router-controller: xcube_hub.controllers.users_controller
  /users:
    get:
      tags:
      - users
      summary: Get all users by service name
      description: |
        Get all users by service name
      operationId: get_users
      security:
      - oAuthorization:
        - read:users
      x-openapi-router-controller: xcube_hub.controllers.users_controller
  /cubegens:
    get:
      tags:
      - cubegens
      summary: List cubegens
      description: |
        List user cubegens
      operationId: get_cubegens
      security:
      - oAuthorization:
        - read:cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens_controller
    put:
      tags:
      - cubegens
      summary: Create a job
      description: |
        Create a job
      operationId: create_job
      security:
      - oAuthorization:
        - write:job
      x-openapi-router-controller: xcube_hub.controllers.cubegens_controller
    delete:
      tags:
      - cubegens
      summary: Delete all cubegens
      description: |
        Delete all cubegens
      operationId: delete_cubegens
      security:
      - oAuthorization:
        - write:job
      x-openapi-router-controller: xcube_hub.controllers.cubegens_controller
  /cubegens/{job_id}:
    get:
      tags:
      - cubegens
      summary: List specific job
      description: |
        List specific job
      operationId: get_job
      security:
      - oAuthorization:
        - read:cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens_controller
    delete:
      tags:
      - cubegens
      summary: Delete a job
      description: |
        Delete a job
      operationId: delete_job
      security:
      - oAuthorization:
        - write:cubegens
      x-openapi-router-controller: xcube_hub.controllers.cubegens_controller
  /cubegens/{job_id}/callbacks:
    get:
      tags:
      - callbacks
      summary: Get list of callbacks for a job
      description: Get list of callbacks for a job
      operationId: get_callbacks_by_job_id
      security:
      - oAuthorization:
        - read:callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks_controller
    put:
      tags:
      - callbacks
      summary: Add a callback for a job
      description: Add a callbacks for a job
      operationId: put_callback_by_job_id
      security:
      - oAuthorization:
        - write:callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks_controller
    delete:
      tags:
      - callbacks
      summary: Clear callbacks for a job
      description: Clear callbacks for a job
      operationId: delete_callbacks_by_job_id
      security:
      - oAuthorization:
        - write:callbacks
      x-openapi-router-controller: xcube_hub.controllers.callbacks_controller
  /oauth/token:
    post:
      tags:
      - oauth
      summary: Get authorization token
      description: Get authorization token
      operationId: oauth_token_post
      security:
      - oAuthorization:
        - read:oauth_token
      x-openapi-router-controller: xcube_hub.controllers.oauth_controller
components:
  securitySchemes:
    oAuthorization:
      type: oauth2
      description: This API uses OAuth 2 with the implicit grant flow.
      flows:
        implicit:
          authorizationUrl: https://edc.eu.auth0.com/authorize
          scopes:
            read_job: Read job status and result
            submit_job: Submit cubegens to the K8s cluster
            read_punits: Allow reading the punits level of a user
            read_callbacks: Allow reading callbacks
        clientCredentials:
          tokenUrl: https://edc.eu.auth0.com/oauth/token
          scopes:
            read_job: Read job status and result
            read_punits: Allow reading the punits level of a user
            put_punits: Allow adding punits to and remove punits from a user
            read_callbacks: Allow reading callbacks
            put_callbacks: Allow reading callbacks
            delete_callbacks: Allow reading callbacks
      x-tokenInfoFunc: xcube_hub.controllers.authorization_controller.check_oAuthorization
      x-scopeValidateFunc: xcube_hub.controllers.authorization_controller.validate_scope_oAuthorization

