# This workflows will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: test-xcube-gen-api

on: [push, pull_request]
    
jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba
    - name: install local
      run: |
        source activate xcube-gen
        pip install codecov
        pip install .
    - name: test
      run: |
        source activate xcube-gen
        pytest -v --cov=xcube_gen
        codecov
        
